modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LESSER GENERAL PUBLIC LICENSE V3.0"

[[mods]]
modId = "iceandfirereborn"
version = "${version}"
displayName = "Ice and Fire: Reborn"
authors = "Muluk"
description = '''An expansion mod that enhances and rebalances Ice and Fire: Dragons.'''
#logoFile = ""

[[dependencies.iceandfirereborn]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfirereborn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfirereborn]]
modId="iceandfire"
mandatory=false
versionRange="[2.1.13-1.20.1,)"
ordering="NONE"
side="BOTH"
